version: '3.8'

services:
  mysql:
    image: docker-0.unsee.tech/mysql:5.7
    # image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    # container_name: mysql # 容器名称
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_HOST: localhost
    ports:
      - "3306:3306"  # 暴露到宿主机
    volumes:
      - mysql_data:/var/lib/mysql  # 数据持久化
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost","-u","root", "-ppassword"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  mysql_data: