name: webAi
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud//pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - libffi=3.4.4
  - openssl=3.0.16
  - pip=25.0
  - python=3.10.14
  - semantic_version=2.10.0
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025a
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.16
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anyio==4.9.0
      - async-timeout==5.0.1
      - asyncmy==0.2.10
      - attr==0.3.2
      - attrs==25.3.0
      - blinker==1.9.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - colorama==0.4.6
      - discord-py==2.5.2
      - ecdsa==0.19.1
      - exceptiongroup==1.2.2
      - fastapi==0.115.12
      - flask==3.1.0
      - frozenlist==1.5.0
      - greenlet==3.1.1
      - h11==0.14.0
      - idna==3.10
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - jose==1.0.0
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - multidict==6.3.2
      - numpy==1.26.4
      - passlib==1.7.4
      - propcache==0.3.1
      - pyasn1==0.4.8
      - pydantic==2.11.2
      - pydantic-core==2.33.1
      - python-jose==3.4.0
      - python-multipart==0.0.20
      - requests==2.32.3
      - rsa==4.9
      - six==1.17.0
      - sniffio==1.3.1
      - sqlalchemy==2.0.40
      - starlette==0.46.1
      - sympy==1.13.3
      - traitlets==5.14.3
      - typing-extensions==4.13.1
      - typing-inspection==0.4.0
      - urllib3==2.3.0
      - uvicorn==0.34.0
      - werkzeug==3.1.3
      - yarl==1.19.0