version: '3.8'

services:
  frontend:
    build:
      context: ./webAi_frontEnd
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - backend
    environment:
      - VITE_BACK_END_URL=http://backend:8889
    networks:
      - app-network
    restart: unless-stopped

  mysql:
    image: docker-0.unsee.tech/mysql:5.7
    # image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    # container_name: mysql # 容器名称
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"  # 暴露到宿主机
    volumes:
      - mysql_data:/var/lib/mysql  # 数据持久化
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: ./webAi_backEnd
      dockerfile: Dockerfile
    ports:
      - "8889:8889"
    volumes:
      - ./webAi_backEnd:/app
      - ./uploads:/app/uploads
    environment:
      - PORT=8889
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local

networks:
  app-network:
    driver: bridge