version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - backend
    environment:
      - VITE_BACK_END_URL=backend:8889
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8889:8889"
    volumes:
      - ./app:/app/app
      - ./uploads:/app/uploads
    environment:
      - PORT=8889
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge